# Environments
dt: 0.001
norm:
  # fT: 30
  action: 1
  obs:
    [1, 1, 1,  # F_des
    1, 1, 1]  # omega
  # n_des: [0.1, 0.1, 1]
  # omega: [10, 10, 50]


# Inner RL parameters
Q: [20, 20, 0, 0, 0]
R: [1, 1, 1, 1]
s: 1
# obs_to_state_index: [1, 2, 4, 5, 6]

# Preprocessing parameters
preprocess_path: "data/preprocess"
prep_max_t: 2
num_tasks: 100
freevar_max: 0.6
num_transitions_per_task: 1500
record_dt: 0.01

# Dataset parameters
transit_size: 1000
context_size: 50
num_frames: 8

# Training hyperparameters
x_dim: 5
u_dim: 4
z_dim: 50
# Periods
num_epochs: 1000
model_save_period: 50
batch_size: 10
stream_period: 50
log_period: 50

cnt_weight: 1
mch_weight: 1
lyap_weight: 10

# Testing parameters
test:
  max_t: 20
  num_epochs: 5000
  stream_period: 50
  log_period: 50
tsne:
  n_components: 2
  perplexity: 8
  n_iter: 10000
  init: "random"
  learning_rate: "auto"
