env_config:
  fkw:
    dt: 0.01
    max_t: 20
  state_space:
    pos:
      low: [-5., -5., -15.]
      high: [5., 5., -5.]
    vel:
      low: [-5., -5., -5.]
      high: [5., 5., 5.]
    angles:
      low: [-30., -30., -360.]  # deg
      high: [30., 30., 360.]  # deg
    omega:
      low: [-10., -10., -10.]
      high: [10., 10., 10.]
  obs_des: [
    0., 0., -5.,  # pos
    0., 0., 0.,  # vel
    0., 0., 0.,  # angles
    0., 0., 0.,  # omega
  ]
  flat_Q: [
    10, 10, 10,  # pos
    1, 1, 1,  # vel
    100, 100, 100,  # angles
    10, 10, 10,  # omega
  ]
  flat_R: [1, 1, 1, 1]

config:
  env: "quadrotor"
  framework: "torch"
  num_gpus: 0
  lr: 1.e-3
  gamma: 0.99

tune:
  run_or_experiment: "PPO"
  stop:
    training_iteration: 1000
  local_dir: "./ray-results"
  checkpoint_freq: 30
  checkpoint_at_end: true
  num_samples: 10
